sudo: false

language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: true
node_js:
  - '8'
deploy:
  provider: npm
  email: "michaelhartmayer@gmail.com"
  api_key:
    secure: 1X/XXidevkuyh6B18eV9oLOeD1u07M6M0vrH7MJkKogR8bWdhF7W8QZ7zUiD+UJsu757OZvJh7VvEgOXYh2Gk4M11H4c1Nzxf5V4tTc1LUUAI4f1EUpG7SwGTqP2GWlWD5sCRORgc+BgpjsbUiy23iKcqZGabIfuRh0oXYpTSZaThhGVFX9npZGLki7NIrrxEY9Gg8CWhVJqoP/tCqsPg0lLlyHYOhecjRE72XF7DzZIkNFLOW7CsbEiDmQQMdxFlcFCjUFRNtswrSuy5NpAm9z0o9aErquFefRZizuix/FRjnvY4YmEJLfnZM3PjUE2QlFVafVcsiyIGFdwE/8nUjbm6jf47i7DZuYoCvDjmP3SteQDGRTbW+nKJq+1hLseQgxXGAKhh5/qbmReQNgpnjbpw3foY/XCjJS9rrw6wUXMq/yvdbyJ9pyObVoa+750Ci7QIHx/qqY+dPp65OthYmE44I85WWb6DxTXj+Loll75OpHutvikC1Zv7Mh9JXKvNrdJ2BOpDjKILSxU0Xn4sLJBjNHpd+ad1WXSdLlNa8aOeR5Qr1jTL0chbhuSgSSK1m2puqdfvD1BIwdaLOoDCv4z2nZV7cqNLo9K9ClfUN0a7isnxcyG7MD32h9/HblEnrJz5ke7rxmpGcy5Foj6/aje3QipFsBLRQ+MkBXR61s=
  on:
    branch: master
